# Example SAM CLI configuration file
# Copy this file to samconfig.toml and customize with your values

version = 0.1

[default]
[default.global.parameters]
stack_name = "kartay-finance-api"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"  # CHANGE THIS to your preferred AWS region
parameter_overrides = [
    "Environment=production",
    # Set these parameters via command line when deploying:
    # sam deploy --parameter-overrides MongoDBUrl="your-url" GoogleApiKey="your-key"
]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Production environment
[production]
[production.deploy.parameters]
stack_name = "kartay-finance-api-prod"
region = "us-east-1"  # CHANGE THIS
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = [
    "Environment=production",
]

# Staging environment
[staging]
[staging.deploy.parameters]
stack_name = "kartay-finance-api-staging"
region = "us-east-1"  # CHANGE THIS
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = [
    "Environment=staging",
]

# Development environment
[development]
[development.deploy.parameters]
stack_name = "kartay-finance-api-dev"
region = "us-east-1"  # CHANGE THIS
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
parameter_overrides = [
    "Environment=development",
]

