name: CI - Tests and Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-coverage:
    name: Test & Coverage (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-mock

    - name: Set test environment variables
      run: |
        echo "MONGODB_URL=mongodb://localhost:27017/" >> $GITHUB_ENV
        echo "MONGODB_DATABASE=finance_tracking_test" >> $GITHUB_ENV
        echo "GOOGLE_API_KEY=test_api_key_for_ci" >> $GITHUB_ENV
        echo "GENAI_MODEL=gemini-1.5-flash-latest" >> $GITHUB_ENV


    - name: Run all tests with coverage
      run: |
        pytest -m unit --cov=src --cov=api --cov-branch --cov-report=xml --cov-report=term-missing

    - name: Upload coverage reports to Codecov
      if: matrix.python-version == '3.13'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: python-${{ matrix.python-version }}
        fail_ci_if_error: false


