name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-mock

    - name: Set environment variables for testing
      run: |
        echo "MONGODB_URL=mongodb://localhost:27017/" >> $GITHUB_ENV
        echo "MONGODB_DATABASE=finance_tracking_test" >> $GITHUB_ENV
        echo "GOOGLE_API_KEY=test_api_key_for_ci" >> $GITHUB_ENV
        echo "GENAI_MODEL=gemini-1.5-flash-latest" >> $GITHUB_ENV

    - name: Wait for MongoDB
      run: |
        sleep 5
        mongosh --eval "db.version()"

    - name: Run unit tests
      run: |
        pytest -m "not integration" --cov=src --cov-report=xml --cov-report=term

    - name: Run integration tests
      run: |
        pytest -m integration --no-cov

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.13'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Generate coverage badge
      if: matrix.python-version == '3.13'
      run: |
        pip install coverage-badge
        coverage-badge -o coverage.svg -f

    - name: Upload coverage badge
      if: matrix.python-version == '3.13'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: coverage.svg

